openapi: 3.0.0
info:
  title: S&B - StarAtlas Trades API
  description: This is the Skull&Bones Trades API V2
  contact:
    email: skullandbonesdao@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://api.skullnbones.xyz/v2
    description: API V2 Endpoint
  - url: https://localhost/v2
    description: API V2 Endpoint
tags:
  - name: UDF
    description: UDF Compatible API Calls
paths:
  /:
    get:
      tags:
        - UDF
      summary: status
      description: |
        Gets a status message
      operationId: getStatus
      responses:
        "200":
          description: status message resutlt
          content:
            text/plain:
              schema:
                type: string
                example: Weclome to S&B StarAtlas Trades API
                x-content-type: text/plain
        "400":
          description: error
        "404":
          description: not found
      x-swagger-router-controller: UDF
  /time:
    get:
      tags:
        - UDF
      summary: time
      description: |
        Gets server time
      operationId: getTime
      responses:
        "200":
          description: time message resutlt
          content:
            text/plain:
              schema:
                type: number
                example: 1662761714
                x-content-type: text/plain
        "400":
          description: error
        "404":
          description: not found
      x-swagger-router-controller: UDF
  /config:
    get:
      tags:
        - UDF
      summary: src
      description: |
        Gets a config message
      operationId: getConfig
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        "400":
          description: error
        "404":
          description: not found
      x-swagger-router-controller: UDF
  /symbol_info:
    get:
      tags:
        - UDF
      summary: symbol into
      description: |
        Gets a symbols info message
      operationId: geSymbolInfo
      responses:
        "200":
          description: returns symbols info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SymbolInfo'
        "400":
          description: error
        "404":
          description: not found
      x-swagger-router-controller: UDF
  /symbols:
    get:
      tags:
        - UDF
      summary: symbol into
      description: |
        Gets a symbol info message
      operationId: geSymbol
      parameters:
        - name: symbol
          in: query
          description: trading pair symbol
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: returns symbol info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Symbol'
        "400":
          description: error
        "404":
          description: not found
      x-swagger-router-controller: UDF
  /search:
    get:
      tags:
        - UDF
      summary: symbol into
      description: |
        Gets a symbol info message
      operationId: geSearchSymbol
      parameters:
        - name: query
          in: query
          description: trading pair symbol
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: limit
          in: query
          description: limit results
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: type
          in: query
          description: type
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: exchange
          in: query
          description: exchange
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: returns symbol info
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SearchSymbol'
                x-content-type: application/json
        "400":
          description: error
        "404":
          description: not found
      x-swagger-router-controller: UDF
  /history:
    get:
      tags:
        - UDF
      summary: history object
      description: |
        Gets a symbol info message
      operationId: geHistoryElement
      parameters:
        - name: symbol
          in: query
          description: trading pair symbol
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: from
          in: query
          description: timestamp from
          required: false
          style: form
          explode: true
          schema:
            type: number
        - name: to
          in: query
          description: timestamp to
          required: false
          style: form
          explode: true
          schema:
            type: number
        - name: resolution
          in: query
          description: time resolution
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: countback
          in: query
          description: counter
          required: false
          style: form
          explode: true
          schema:
            type: number
        - name: currencyCode
          in: query
          description: symbol-cde
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: returns symbol info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistoryElement'
        "400":
          description: error
        "404":
          description: not found
      x-swagger-router-controller: UDF
components:
  schemas:
    Config:
      required:
        - exchnages
      type: object
      properties:
        exchanges:
          type: array
          items:
            $ref: '#/components/schemas/Exchange'
        symbols_types:
          type: array
          items:
            $ref: '#/components/schemas/SymbolsType'
        supported_resolutions:
          type: array
          items:
            type: string
            example: 1D
        homePage:
          type: string
          format: url
          example: https://www.acme-corp.com
        supports_search:
          type: boolean
          example: true
        supports_group_request:
          type: boolean
          example: false
        supports_marks:
          type: boolean
          example: false
        supports_timescale_marks:
          type: boolean
          example: false
        supports_time:
          type: boolean
          example: true
      example:
        supports_marks: false
        supports_time: true
        exchanges:
          - name: StarAtlas
            value: SA
            desc: StarAtlas Exch
          - name: StarAtlas
            value: SA
            desc: StarAtlas Exch
        supports_search: true
        supports_group_request: false
        symbols_types:
          - name: Cryptocurrency
            value: crypto
          - name: Cryptocurrency
            value: crypto
        supported_resolutions:
          - 1D
          - 1D
        homePage: https://www.acme-corp.com
        supports_timescale_marks: false
    SymbolInfo:
      type: object
      properties:
        symbol:
          type: array
          items:
            type: string
            example: PX4ATLAS
        ticker:
          type: array
          items:
            type: string
            example: PX4ATLAS
        name:
          type: array
          items:
            type: string
            example: PX4ATLAS
        full_name:
          type: array
          items:
            type: string
            example: PX4ATLAS
        description:
          type: array
          items:
            type: string
            example: PX4 ATLAS
        exchange:
          type: string
          example: SA
        listed_exchange:
          type: string
          example: SA
        type:
          type: string
          example: crypto
        currency_code:
          type: array
          items:
            type: string
            example: BTC
        session:
          type: string
          example: 24x7
        timezone:
          type: string
          example: UTC
        minmovement:
          type: number
          example: 1
        minmov:
          type: number
          example: 1
        minmovement2:
          type: number
          example: 0
        minmov2:
          type: number
          example: 0
        pricescale:
          type: array
          items:
            type: number
            example: 100
        supported_resolutions:
          type: array
          items:
            type: string
            example: "1"
        has_intraday:
          type: boolean
          example: true
        has_daily:
          type: boolean
          example: true
        has_weekly_and_monthly:
          type: number
        data_status:
          type: string
          example: streaming
      example:
        symbol:
          - PX4ATLAS
          - PX4ATLAS
        ticker:
          - PX4ATLAS
          - PX4ATLAS
        has_daily: true
        has_weekly_and_monthly: 0.80082819046101150206595775671303272247314453125
        minmov2: 0
        session: 24x7
        timezone: UTC
        has_intraday: true
        description:
          - PX4 ATLAS
          - PX4 ATLAS
        listed_exchange: SA
        supported_resolutions:
          - "1"
          - "1"
        type: crypto
        currency_code:
          - BTC
          - BTC
        full_name:
          - PX4ATLAS
          - PX4ATLAS
        name:
          - PX4ATLAS
          - PX4ATLAS
        minmovement: 1
        minmov: 1
        exchange: SA
        pricescale:
          - 100
          - 100
        minmovement2: 0
        data_status: streaming
    Symbol:
      type: object
      properties:
        symbol:
          type: string
          example: PX4ATLAS
        ticker:
          type: string
          example: PX4ATLAS
        name:
          type: string
          example: PX4ATLAS
        full_name:
          type: string
          example: PX4ATLAS
        description:
          type: string
          example: PX4 ATLAS
        exchange:
          type: string
          example: SA
        listed_exchange:
          type: string
          example: SA
        type:
          type: string
          example: crypto
        currency_code:
          type: string
          example: BTC
        session:
          type: string
          example: 24x7
        timezone:
          type: string
          example: UTC
        minmovement:
          type: number
          example: 1
        minmov:
          type: number
          example: 1
        minmovement2:
          type: number
          example: 0
        minmov2:
          type: number
          example: 0
        pricescale:
          type: array
          items:
            type: number
            example: 100
        supported_resolutions:
          type: array
          items:
            type: string
            example: "1"
        has_intraday:
          type: boolean
          example: true
        has_daily:
          type: boolean
          example: true
        has_weekly_and_monthly:
          type: number
        data_status:
          type: string
          example: streaming
      example:
        symbol: PX4ATLAS
        ticker: PX4ATLAS
        has_daily: true
        has_weekly_and_monthly: 0.80082819046101150206595775671303272247314453125
        minmov2: 0
        session: 24x7
        timezone: UTC
        has_intraday: true
        description: PX4 ATLAS
        listed_exchange: SA
        supported_resolutions:
          - "1"
          - "1"
        type: crypto
        currency_code: BTC
        full_name: PX4ATLAS
        name: PX4ATLAS
        minmovement: 1
        minmov: 1
        exchange: SA
        pricescale:
          - 100
          - 100
        minmovement2: 0
        data_status: streaming
    SearchSymbol:
      type: object
      properties:
        symbol:
          type: string
          example: PX4ATLAS
        full_name:
          type: string
          example: PX4ATLAS
        description:
          type: string
          example: PX4 ATLAS
        exchange:
          type: string
          example: SA
        ticker:
          type: string
          example: PX4ATLAS
        type:
          type: string
          example: crypto
      example:
        symbol: PX4ATLAS
        ticker: PX4ATLAS
        full_name: PX4ATLAS
        description: PX4 ATLAS
        exchange: SA
        type: crypto
    HistoryElement:
      type: object
      properties:
        s:
          type: string
          example: ok
        t:
          type: array
          items:
            type: number
            example: 12322121
        c:
          type: array
          items:
            type: number
            example: 12322121
        o:
          type: array
          items:
            type: number
            example: 12322121
        h:
          type: array
          items:
            type: number
            example: 12322121
        l:
          type: array
          items:
            type: number
            example: 12322121
        v:
          type: array
          items:
            type: number
            example: 12322121
      example:
        s: ok
        c:
          - 12322121
          - 12322121
        t:
          - 12322121
          - 12322121
        v:
          - 12322121
          - 12322121
        h:
          - 12322121
          - 12322121
        l:
          - 12322121
          - 12322121
        o:
          - 12322121
          - 12322121
    Exchange:
      required:
        - exchange
      type: object
      properties:
        value:
          type: string
          example: SA
        name:
          type: string
          example: StarAtlas
        desc:
          type: string
          example: StarAtlas Exch
      example:
        name: StarAtlas
        value: SA
        desc: StarAtlas Exch
    SymbolsType:
      type: object
      properties:
        value:
          type: string
          example: crypto
        name:
          type: string
          example: Cryptocurrency
      example:
        name: Cryptocurrency
        value: crypto
